### ISSUE TITLE
Add validations to makefile/bicep input parameters 

### ISSUE THREAD

**Issue by Justrebl** [zlatko-ms/az-capps-private#14]
Some services on Azure have restrictions to their max size (Key vault limited to 24 characters for example). 
Having a validation to the max size of inputs could help to fail fast, and avoid waiting to get to the step of the failing resource provisionning before knowing it cannot get to the end as is.

**Comment by zlatko-ms** [comment]
@Justrebl Wasn't that fixed a loooong time ago ?

**Comment by zlatko-ms** [comment]
Closing this one it was fixed quite some time ago.
